/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.screen;

import br.ufmt.genericlexerseb.LanguageType;
import br.ufmt.preprocessing.ProcessorTiff;
import br.ufmt.preprocessing.exceptions.TiffErrorBandsException;
import br.ufmt.preprocessing.exceptions.TiffNotFoundException;
import br.ufmt.preprocessing.utils.DataFile;
import br.ufmt.util.Constant;
import br.ufmt.util.EquationEditor;
import br.ufmt.util.FloatEditor;
import br.ufmt.util.GeneSEBean;
import br.ufmt.util.Image;
import br.ufmt.util.Util;
import br.ufmt.util.VariableEditor;
import com.sun.media.jai.codec.FileSeekableStream;
import com.sun.media.jai.codec.ImageCodec;
import com.sun.media.jai.codec.ImageDecoder;
import com.sun.media.jai.codec.SeekableStream;
import com.sun.media.jai.codec.TIFFDecodeParam;
import java.awt.image.Raster;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.gdal.gdal.Dataset;
import org.gdal.gdal.Driver;
import org.gdal.gdal.gdal;
import org.gdal.gdalconst.gdalconstConstants;

/**
 *
 * @author raphael
 */
public class SEBALLandSat5JPanel extends ScreenAbstract {

    private File file;
    private final static String[] extensions = new String[]{"tiff", "tif"};
    private final static String saveExtension = "sebal";
    private Driver driver;

    /**
     * Creates new form SEBALLandSat5JPanel
     */
    public SEBALLandSat5JPanel() {
        initComponents();
        gdal.AllRegister();

        driver = gdal.GetDriverByName("GTiff");
        driver.Register();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabjTabbedPane = new javax.swing.JTabbedPane();
        bandsjPanel = new javax.swing.JPanel();
        bandsjScrollPane = new javax.swing.JScrollPane();
        bandsjTable = new javax.swing.JTable();
        constantjPanel = new javax.swing.JPanel();
        addConstantjButton = new javax.swing.JButton();
        deleteConstantjButton = new javax.swing.JButton();
        constantjScrollPane = new javax.swing.JScrollPane();
        constantjTable = new javax.swing.JTable();
        forVariablejPanel = new javax.swing.JPanel();
        addForVariablejButton = new javax.swing.JButton();
        deleteForVariablejButton = new javax.swing.JButton();
        forVariablejScrollPane = new javax.swing.JScrollPane();
        forVariablejTable = new javax.swing.JTable();
        upForVariablejButton = new javax.swing.JButton();
        downForVariablejButton = new javax.swing.JButton();
        forEachValuejPanel = new javax.swing.JPanel();
        addForEachValuejButton = new javax.swing.JButton();
        deleteForEachValuejButton = new javax.swing.JButton();
        forEachValuejScrollPane = new javax.swing.JScrollPane();
        forEachValuejTable = new javax.swing.JTable();
        upForEachValuejButton = new javax.swing.JButton();
        downForEachValuejButton = new javax.swing.JButton();
        filejLabel = new javax.swing.JLabel();
        uploadjButton = new javax.swing.JButton();
        uploadjLabel = new javax.swing.JLabel();
        executejButton = new javax.swing.JButton();

        bandsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bandsjScrollPane.setViewportView(bandsjTable);
        if (bandsjTable.getColumnModel().getColumnCount() > 0) {
            bandsjTable.getColumnModel().getColumn(0).setResizable(false);
            bandsjTable.getColumnModel().getColumn(0).setHeaderValue(Util.getMessage("bands"));
            bandsjTable.getColumnModel().getColumn(1).setResizable(false);
            bandsjTable.getColumnModel().getColumn(1).setHeaderValue(Util.getMessage("value"));
        }

        javax.swing.GroupLayout bandsjPanelLayout = new javax.swing.GroupLayout(bandsjPanel);
        bandsjPanel.setLayout(bandsjPanelLayout);
        bandsjPanelLayout.setHorizontalGroup(
            bandsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandsjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
        );
        bandsjPanelLayout.setVerticalGroup(
            bandsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandsjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabjTabbedPane.addTab(Util.getMessage("bands"), bandsjPanel);

        addConstantjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/add.png"))); // NOI18N
        addConstantjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConstantjButtonActionPerformed(evt);
            }
        });

        deleteConstantjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/delete.png"))); // NOI18N
        deleteConstantjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConstantjButtonActionPerformed(evt);
            }
        });

        constantjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        constantjScrollPane.setViewportView(constantjTable);
        if (constantjTable.getColumnModel().getColumnCount() > 0) {
            constantjTable.getColumnModel().getColumn(0).setResizable(false);
            constantjTable.getColumnModel().getColumn(0).setHeaderValue(Util.getMessage("constant"));
            constantjTable.getColumnModel().getColumn(1).setResizable(false);
            constantjTable.getColumnModel().getColumn(1).setHeaderValue(Util.getMessage("value"));
        }
        constantjTable.getColumnModel().getColumn(0).setCellEditor(new VariableEditor());
        constantjTable.getColumnModel().getColumn(1).setCellEditor(new FloatEditor());

        javax.swing.GroupLayout constantjPanelLayout = new javax.swing.GroupLayout(constantjPanel);
        constantjPanel.setLayout(constantjPanelLayout);
        constantjPanelLayout.setHorizontalGroup(
            constantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(constantjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(constantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addConstantjButton)
                    .addComponent(deleteConstantjButton))
                .addGap(18, 18, 18)
                .addComponent(constantjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        constantjPanelLayout.setVerticalGroup(
            constantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(constantjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(constantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(constantjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(constantjPanelLayout.createSequentialGroup()
                        .addComponent(addConstantjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteConstantjButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        tabjTabbedPane.addTab(Util.getMessage("constant"), constantjPanel);

        addForVariablejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/add.png"))); // NOI18N
        addForVariablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForVariablejButtonActionPerformed(evt);
            }
        });

        deleteForVariablejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/delete.png"))); // NOI18N
        deleteForVariablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteForVariablejButtonActionPerformed(evt);
            }
        });

        forVariablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        forVariablejScrollPane.setViewportView(forVariablejTable);
        if (forVariablejTable.getColumnModel().getColumnCount() > 0) {
            forVariablejTable.getColumnModel().getColumn(0).setResizable(false);
            forVariablejTable.getColumnModel().getColumn(0).setHeaderValue(Util.getMessage("forVariable"));
        }
        forVariablejTable.getColumnModel().getColumn(0).setCellEditor(new EquationEditor());

        upForVariablejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/arrow_up.png"))); // NOI18N
        upForVariablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upForVariablejButtonActionPerformed(evt);
            }
        });

        downForVariablejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/arrow_down.png"))); // NOI18N
        downForVariablejButton.setPreferredSize(new java.awt.Dimension(34, 34));
        downForVariablejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downForVariablejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forVariablejPanelLayout = new javax.swing.GroupLayout(forVariablejPanel);
        forVariablejPanel.setLayout(forVariablejPanelLayout);
        forVariablejPanelLayout.setHorizontalGroup(
            forVariablejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forVariablejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forVariablejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addForVariablejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteForVariablejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upForVariablejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downForVariablejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(forVariablejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        forVariablejPanelLayout.setVerticalGroup(
            forVariablejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forVariablejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forVariablejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forVariablejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(forVariablejPanelLayout.createSequentialGroup()
                        .addComponent(addForVariablejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteForVariablejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upForVariablejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downForVariablejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        tabjTabbedPane.addTab(Util.getMessage("forVariable"), forVariablejPanel);

        addForEachValuejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/add.png"))); // NOI18N
        addForEachValuejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addForEachValuejButtonActionPerformed(evt);
            }
        });

        deleteForEachValuejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/delete.png"))); // NOI18N
        deleteForEachValuejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteForEachValuejButtonActionPerformed(evt);
            }
        });

        forEachValuejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        forEachValuejScrollPane.setViewportView(forEachValuejTable);
        if (forEachValuejTable.getColumnModel().getColumnCount() > 0) {
            forEachValuejTable.getColumnModel().getColumn(0).setResizable(false);
            forEachValuejTable.getColumnModel().getColumn(0).setHeaderValue(Util.getMessage("forEachValue"));
        }
        forEachValuejTable.getColumnModel().getColumn(0).setCellEditor(new EquationEditor());

        upForEachValuejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/arrow_up.png"))); // NOI18N
        upForEachValuejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upForEachValuejButtonActionPerformed(evt);
            }
        });

        downForEachValuejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/arrow_down.png"))); // NOI18N
        downForEachValuejButton.setPreferredSize(new java.awt.Dimension(34, 34));
        downForEachValuejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downForEachValuejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forEachValuejPanelLayout = new javax.swing.GroupLayout(forEachValuejPanel);
        forEachValuejPanel.setLayout(forEachValuejPanelLayout);
        forEachValuejPanelLayout.setHorizontalGroup(
            forEachValuejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forEachValuejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forEachValuejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addForEachValuejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteForEachValuejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upForEachValuejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downForEachValuejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(forEachValuejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        forEachValuejPanelLayout.setVerticalGroup(
            forEachValuejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forEachValuejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forEachValuejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forEachValuejScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(forEachValuejPanelLayout.createSequentialGroup()
                        .addComponent(addForEachValuejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteForEachValuejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upForEachValuejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downForEachValuejButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        tabjTabbedPane.addTab(Util.getMessage("forEachValue"), forEachValuejPanel);

        filejLabel.setText(Util.getMessage("file"));

        uploadjButton.setText(Util.getMessage("upload"));
        uploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadjButtonActionPerformed(evt);
            }
        });

        uploadjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        executejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufmt/resource/executar.png"))); // NOI18N
        executejButton.setText(Util.getMessage("execute"));
        executejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(executejButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabjTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(filejLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(uploadjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uploadjButton))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filejLabel)
                        .addComponent(uploadjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uploadjButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabjTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executejButton)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadjButtonActionPerformed
        // TODO add your handling code here:
        file = Util.uploadFile(extensions, this);
        if (file != null) {
            uploadjLabel.setText(file.getPath());

            int tam;

            boolean add = true;

            Dataset entrada = gdal.Open(file.getPath(), gdalconstConstants.GA_ReadOnly);

            int bands = entrada.GetRasterCount();
            int height = entrada.GetRasterYSize();
            int width = entrada.GetRasterXSize();

            tam = height * width;
            System.out.println("Add W:" + width + " H:" + height);
            if (bandsjTable.getRowCount() > 0) {
                Image image;
                int tamCompare;
                Dataset rasterCompare;
                for (int i = 0; i < bandsjTable.getRowCount(); i++) {
                    image = (Image) bandsjTable.getValueAt(i, 0);
                    rasterCompare = gdal.Open(image.getFile().getPath(), gdalconstConstants.GA_ReadOnly);
                    tamCompare = rasterCompare.GetRasterYSize() * rasterCompare.GetRasterXSize();
                    System.out.println("I:" + (i + 1) + " W:" + rasterCompare.GetRasterXSize() + " H:" + rasterCompare.GetRasterYSize());
                    if (tamCompare != tam) {
                        add = false;
                        break;
                    }
                }
            }

            if (add) {
                DefaultTableModel dfm = (DefaultTableModel) bandsjTable.getModel();
                Image aux;
                if (bands > 1) {
                    for (int i = 0; i < bands; i++) {
                        aux = new Image(file.getName(), "pixel" + (i + 1), file);
                        dfm.addRow(new Object[]{aux, aux.getValue()});
                    }
                } else {
                    String vet[] = file.getName().split("\\.");
                    StringBuilder name = new StringBuilder(vet[0]);
                    for (int i = 1; i < vet.length - 1; i++) {
                        name.append(vet[i]);
                    }
                    aux = new Image(file.getName(), name.toString(), file);
                    dfm.addRow(new Object[]{aux, aux.getValue()});
                }
            } else {
                JOptionPane.showMessageDialog(this, Util.getMessage("error.size") + " X:" + width + " Y:" + height);
            }

        } else {
            uploadjLabel.setText("");
        }
    }//GEN-LAST:event_uploadjButtonActionPerformed

    private void addConstantjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConstantjButtonActionPerformed
        // TODO add your handling code here:
        Util.addLineTable(constantjTable, 2);
    }//GEN-LAST:event_addConstantjButtonActionPerformed

    private void deleteConstantjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConstantjButtonActionPerformed
        // TODO add your handling code here:
        Util.removeTable(constantjTable);
    }//GEN-LAST:event_deleteConstantjButtonActionPerformed

    private void addForVariablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForVariablejButtonActionPerformed
        // TODO add your handling code here:
        Util.addLineTable(forVariablejTable, 1);
    }//GEN-LAST:event_addForVariablejButtonActionPerformed

    private void deleteForVariablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteForVariablejButtonActionPerformed
        // TODO add your handling code here:
        Util.removeTable(forVariablejTable);
    }//GEN-LAST:event_deleteForVariablejButtonActionPerformed

    private void addForEachValuejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addForEachValuejButtonActionPerformed
        // TODO add your handling code here:
        Util.addLineTable(forEachValuejTable, 1);
    }//GEN-LAST:event_addForEachValuejButtonActionPerformed

    private void deleteForEachValuejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteForEachValuejButtonActionPerformed
        // TODO add your handling code here:
        Util.removeTable(forEachValuejTable);
    }//GEN-LAST:event_deleteForEachValuejButtonActionPerformed

    private void executejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executejButtonActionPerformed
        // TODO add your handling code here:
        if (bandsjTable.getRowCount() > 0) {
            if (forEachValuejTable.getRowCount() > 0) {
                String path = file.getPath();

                StringBuilder header = new StringBuilder();
                StringBuilder body = new StringBuilder();

                Map<String, Float> variables = new HashMap<String, Float>();
                for (int i = 0; i < constantjTable.getRowCount(); i++) {
                    variables.put((String) constantjTable.getValueAt(i, 0), (Float) constantjTable.getValueAt(i, 1));
                }

                for (int i = 0; i < forVariablejTable.getRowCount(); i++) {
                    header.append((String) forVariablejTable.getValueAt(i, 0)).append("\n");
                }

                for (int i = 0; i < forEachValuejTable.getRowCount(); i++) {
                    body.append((String) forEachValuejTable.getValueAt(i, 0)).append("\n");
                }

                File tiff = file;
                if (tiff.exists() && tiff.getName().endsWith(".tif")) {
                    long time = System.currentTimeMillis();

//                SeekableStream s = null;
                    try {
                        List<DataFile> ret = new ArrayList<DataFile>();
//                    System.out.println("Arq:" + tiff.getName());
                        SeekableStream s = new FileSeekableStream(tiff);
                        TIFFDecodeParam param = null;
                        ImageDecoder dec = ImageCodec.createImageDecoder("tiff", s, param);
                        // Which of the multiple images in the TIFF file do we want to load
                        // 0 refers to the first, 1 to the second and so on.
                        int bands;
                        Raster raster = dec.decodeAsRaster(0);
                        bands = raster.getNumBands();
                        int width = raster.getWidth();
                        int height = raster.getHeight();
                        int tam = width * height;

                        variables.put("width", (float) width);
                        variables.put("height", (float) height);
                        if (bands == 7) {

                            float[][] calibration = new float[][]{
                                {-1.52f, 193.0f, 1957.0f},
                                {-2.84f, 365.0f, 1826.0f},
                                {-1.17f, 264.0f, 1554.0f},
                                {-1.51f, 221.0f, 1036.0f},
                                {-0.37f, 30.2f, 215.0f},
                                {1.2378f, 15.303f, 1.0f},
                                {-0.15f, 16.5f, 80.67f}};

//                        float[] parameterAlbedo = new float[]{0.293f, 0.274f, 0.233f, 0.157f, 0.033f, 0.0f, 0.011f};
                            float[] parameterAlbedo = new float[7];

                            float sum = 0;
                            for (int i = 0; i < calibration.length; i++) {
                                sum += calibration[i][2];
                            }
                            for (int i = 0; i < parameterAlbedo.length; i++) {
                                parameterAlbedo[i] = calibration[i][2] / sum;
                            }
                            parameterAlbedo[5] = 0;

                            String[] nameParameters = new String[]{"pixel1", "pixel2", "pixel3", "pixel4", "pixel5", "pixel6", "pixel7"};

                            Map<String, float[][]> constMatrix = new HashMap<String, float[][]>();
                            constMatrix.put("calibration", calibration);

                            Map<String, float[]> constVetor = new HashMap<String, float[]>();
                            constVetor.put("parameterAlbedo", parameterAlbedo);

                            try {
                                ProcessorTiff processorTiff = new ProcessorTiff(LanguageType.CUDA);
                                ret = processorTiff.execute(header.toString(), body.toString(), path, nameParameters, variables, constVetor, constMatrix);
                            } catch (Exception ex) {
                                JOptionPane.showMessageDialog(this, ex.getMessage());
                            }

                            System.out.println("End");
                        } else {
                            JOptionPane.showMessageDialog(this, new TiffErrorBandsException().getMessage());
                        }

                        s.close();
                        time = System.currentTimeMillis() - time;
                        System.out.println("Tempo:" + time);
                        JOptionPane.showMessageDialog(this, Util.getMessage("execution.sucess"));

                    } catch (IOException ex) {
                        Logger.getLogger(SEBALLandSat5JPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {

                    JOptionPane.showMessageDialog(this, new TiffNotFoundException().getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, Util.getMessage("error.equation"));
            }
        } else {
            JOptionPane.showMessageDialog(this, Util.getMessage("error.image"));
        }
    }//GEN-LAST:event_executejButtonActionPerformed

    private void upForVariablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upForVariablejButtonActionPerformed
        // TODO add your handling code here:
        Util.moveTableUp(forVariablejTable);
    }//GEN-LAST:event_upForVariablejButtonActionPerformed

    private void downForVariablejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downForVariablejButtonActionPerformed
        // TODO add your handling code here:
        Util.moveTableDown(forVariablejTable);
    }//GEN-LAST:event_downForVariablejButtonActionPerformed

    private void upForEachValuejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upForEachValuejButtonActionPerformed
        // TODO add your handling code here:
        Util.moveTableUp(forEachValuejTable);
    }//GEN-LAST:event_upForEachValuejButtonActionPerformed

    private void downForEachValuejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downForEachValuejButtonActionPerformed
        // TODO add your handling code here:
        Util.moveTableDown(forEachValuejTable);
    }//GEN-LAST:event_downForEachValuejButtonActionPerformed

    @Override
    public String[] getExtensions() {
        return extensions;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConstantjButton;
    private javax.swing.JButton addForEachValuejButton;
    private javax.swing.JButton addForVariablejButton;
    private javax.swing.JPanel bandsjPanel;
    private javax.swing.JScrollPane bandsjScrollPane;
    private javax.swing.JTable bandsjTable;
    private javax.swing.JPanel constantjPanel;
    private javax.swing.JScrollPane constantjScrollPane;
    private javax.swing.JTable constantjTable;
    private javax.swing.JButton deleteConstantjButton;
    private javax.swing.JButton deleteForEachValuejButton;
    private javax.swing.JButton deleteForVariablejButton;
    private javax.swing.JButton downForEachValuejButton;
    private javax.swing.JButton downForVariablejButton;
    private javax.swing.JButton executejButton;
    private javax.swing.JLabel filejLabel;
    private javax.swing.JPanel forEachValuejPanel;
    private javax.swing.JScrollPane forEachValuejScrollPane;
    private javax.swing.JTable forEachValuejTable;
    private javax.swing.JPanel forVariablejPanel;
    private javax.swing.JScrollPane forVariablejScrollPane;
    private javax.swing.JTable forVariablejTable;
    private javax.swing.JTabbedPane tabjTabbedPane;
    private javax.swing.JButton upForEachValuejButton;
    private javax.swing.JButton upForVariablejButton;
    private javax.swing.JButton uploadjButton;
    private javax.swing.JLabel uploadjLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setBean(GeneSEBean bean) {
        Util.setBean(bean, constantjTable, forVariablejTable, forEachValuejTable);
    }

    @Override
    public GeneSEBean getBean() {
        return Util.getBean(constantjTable, forVariablejTable, forEachValuejTable);
    }

    @Override
    public String getSaveExtension() {
        return saveExtension;
    }

}
