/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt;

import br.ufmt.screen.SEBALLandSat5JPanel;
import br.ufmt.screen.ScreenAbstract;
import br.ufmt.util.GeneSEBean;
import br.ufmt.util.Util;
import java.awt.Toolkit;
import javax.enterprise.event.Observes;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jboss.weld.environment.se.events.ContainerInitialized;

/**
 *
 * @author raphael
 */
public class MainScreen extends javax.swing.JFrame {

    private ScreenAbstract opened;

    /**
     * Creates new form Principal
     */
    public MainScreen() {
        initComponents();
        filejMenu.setVisible(false);
        setSize(800, 600);
        int height = Toolkit.getDefaultToolkit().getScreenSize().height;
        int width = Toolkit.getDefaultToolkit().getScreenSize().width;
        setLocation((width - getWidth()) / 2, (height - getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentjPanel = new javax.swing.JPanel();
        menujMenuBar = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        openjMenuItem = new javax.swing.JMenuItem();
        savejMenuItem = new javax.swing.JMenuItem();
        screenjMenu = new javax.swing.JMenu();
        sebaljMenuItem = new javax.swing.JMenuItem();
        languagejMenu = new javax.swing.JMenu();
        ptBRjMenuItem = new javax.swing.JMenuItem();
        enUSjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentjPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contentjPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contentjPanel, java.awt.BorderLayout.CENTER);

        filejMenu.setText(Util.getMessage("menu.file")
        );

        openjMenuItem.setText(Util.getMessage("menu.open"));
        openjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openjMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(openjMenuItem);

        savejMenuItem.setText(Util.getMessage("menu.save"));
        savejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(savejMenuItem);

        menujMenuBar.add(filejMenu);

        screenjMenu.setText(Util.getMessage("algorithm"));

        sebaljMenuItem.setText(Util.getMessage("title.landsat5.sebal"));
        sebaljMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sebaljMenuItemActionPerformed(evt);
            }
        });
        screenjMenu.add(sebaljMenuItem);

        menujMenuBar.add(screenjMenu);

        languagejMenu.setText(Util.getMessage("language"));

        ptBRjMenuItem.setText(Util.getMessage("brazil"));
        languagejMenu.add(ptBRjMenuItem);

        enUSjMenuItem.setText(Util.getMessage("english"));
        languagejMenu.add(enUSjMenuItem);

        menujMenuBar.add(languagejMenu);

        setJMenuBar(menujMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sebaljMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sebaljMenuItemActionPerformed
        // TODO add your handling code here:
        opened = new SEBALLandSat5JPanel();
        addContent(opened);
        filejMenu.setVisible(true);
    }//GEN-LAST:event_sebaljMenuItemActionPerformed

    private void openjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openjMenuItemActionPerformed
        // TODO add your handling code here:
        String[] extensions = new String[]{opened.getSaveExtension()};
        GeneSEBean bean = Util.open(Util.uploadFile(extensions, opened));
        opened.setBean(bean);
        JOptionPane.showMessageDialog(this, Util.getMessage("file.loaded"));
    }//GEN-LAST:event_openjMenuItemActionPerformed

    private void savejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejMenuItemActionPerformed
        // TODO add your handling code here:
        String[] extensions = new String[]{opened.getSaveExtension()};
        Util.save(Util.uploadFile(extensions, opened), opened.getBean());
    }//GEN-LAST:event_savejMenuItemActionPerformed

    public void addContent(JPanel panel) {
        contentjPanel.removeAll();
        contentjPanel.add(panel);
        contentjPanel.setVisible(false);
        contentjPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    public void main(@Observes ContainerInitialized event) {

//        String teste  = "Ustar=Uref*k/ln(U_z/z0)";
//        
//        System.out.println(teste.matches("[aA-zZ_][aA-zZ_0-9]*[_(]?[aA-zZ_0-9+-/()\\.\\*=><!]*[)]?[=][aA-zZ_0-9+-/()\\.\\*]+"));
//        Util.isEquationValid(teste);
//        System.exit(1);
        MainScreen screen = new MainScreen();
        screen.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentjPanel;
    private javax.swing.JMenuItem enUSjMenuItem;
    private javax.swing.JMenu filejMenu;
    private javax.swing.JMenu languagejMenu;
    private javax.swing.JMenuBar menujMenuBar;
    private javax.swing.JMenuItem openjMenuItem;
    private javax.swing.JMenuItem ptBRjMenuItem;
    private javax.swing.JMenuItem savejMenuItem;
    private javax.swing.JMenu screenjMenu;
    private javax.swing.JMenuItem sebaljMenuItem;
    // End of variables declaration//GEN-END:variables
}
